version: '2'

services:
  petshop.restapi:
    image: petshop
    container_name: petshop-api
    ports:
      - 32768:80
    build:
      context: .
      dockerfile: PetShop.RestApi/Dockerfile
