version: '2'

services:
  petshop.restapi:
    image: petshop
    container_name: petshop-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 58000:80
      - 58001:443
    build:
      context: .
      dockerfile: PetShop.RestApi/Dockerfile
